### PR TITLE
Form css

### PR DESCRIPTION
**Pull request by DRot88**
by unnested the state, the dropdowns started working and the evt handler works as expected

### CODE REVIEW

**Comment by DRot88** [comment]
image

**Comment by BartHough** [comment]
Wasn’t this all working before?

**Comment by DRot88** [comment]
In short yes, but by refactoring handleTime* to handleChange, we can add 10 new form fields if we wanted and the code would not need to change. 

By unnesting the state (removing the 'field' wrapper) I was able to remove redundant code on multiple lines to make it a little cleaner. 

I had a slight issue with the datepickers which updated state but visually would be reset everytime I chose a date, which isn't happening anymore

**Comment by BartHough** [comment]
Okay and you made sure everything with the map is still working?

**Comment by DRot88** [comment]
Yes it works for me..clicking on the map still moves the pinpoint, and updates the states address, zip, stateLong, stateShort, region

**Review by BartHough — APPROVED** [review]

**Review by BartHough — DISMISSED** [review]
Looks good. Can you squash these three commits together to keep git history on master clean?

I think you'll have to make a new branch, formCSSPR. then merge this branch with that branch using the commands in step 3 [here](https://spin.atomicobject.com/2017/04/23/maintain-clean-git-history/). Then push and open up a new PR from that branch.

**Comment by DRot88** [comment]
while that certainly works, couldn't we just use the drop down next to 'merge pull request' and select 'squash and merge'?

**Comment by BartHough** [comment]
Ah yeah, didn't realize that was an option here.

**Review by BartHough — APPROVED** [review]

**Review by kevharvell — APPROVED** [review]
Nice work, Daniel. Wanted to be sure we document that we want to accordion map/form in order to maximize viewing of chart as per our discussion on Slack

**Pull request merged**
